Pull Request US 07
PedroChaparro/PI202202-alako-frontend pull request #17
Opened 2022-10-11 14:42 UTC by SilviaPabon

Este pull request incluye las tareas de:
- Comunicación con el back-end para enviar las búsquedas del usuario y obtener la repuesta del servidor
- Mostrar los vídeos enviados como respuesta del servidor haciendo uso de las cards desarrolladas

Quedo al pendiente!

2022-10-11 15:26 UTC, PedroChaparro requested changes

2022-10-11 15:26 UTC, PedroChaparro commented on src/index.html
> +							id="url"
Sugiero que este id se cambie por una clase (También los otros casos en los que aplique), ya que los ids [deberían ser únicos en lo posible](https://developer.mozilla.org/en-US/docs/Web/API/Element/id).

2022-10-11 15:26 UTC, PedroChaparro commented on src/script.js
> +	let intervalID = setInterval(async () => {
(Esto es sobre todo para ver qué opinan) Creo que este interval se podría guardar en una variable fuera de la función, para después poder accederlo y cancelarlo (`clearInterval()`). Puede ser útil en el siguiente escenario, pero tiene un contra: 

1. El usuario hace una búsqueda
2. No ha llegado el resultado de la búsqueda pero el usuario hace otra, por lo que habrían dos intervals ejecutándose al tiempo.

Del modo que se me ocurre se podría cancelar el primer interval, pero entonces en la API se quedaría el resultado de esa búsqueda por siempre esperando que en algún momento se contulte la ruta `/obtain`, a no ser que lo eliminemos de otra manera.

2022-10-11 21:31 UTC, Woynert commented on src/script.js
> +	let intervalID = setInterval(async () => {
Algo así cómo hacer un endpoint en la API para cancelar un trabajo.

2022-10-11 22:54 UTC, Woynert requested changes

2022-10-11 22:54 UTC, Woynert commented on src/script.js
> +					const templateCloneTitle = templateClone.getElementById('title');
Complementando a @PedroChaparro emplear `getElementsByClassName("class")[0]` en lugar de `getElementById("id")` en los elementos internos del template. Debido a que el metodo `getElementById` no existe en el tipo Element (devuelto por cloneNode).

2022-10-11 22:54 UTC, Woynert commented on src/script.js
> +					const templateClone = template.content.cloneNode(true);
Esto devuelve un documentFragment que no recibe eventos; utilizar `template.cloneNode(true)` (sin el `content`) que devuelve un Element y si puede recibir eventos.

2022-10-12 22:57 UTC, SilviaPabon commented on src/script.js
> +					const templateClone = template.content.cloneNode(true);
Se realizaron los cambios @Woynert y @PedroChaparro quedo al pendiente.

2022-10-13 10:54 UTC, Woynert reviewed
El botón de lupa parece no servir, es esto intencional?

2022-10-13 15:47 UTC, Woynert approved these changes

2022-10-13 22:33 UTC, andres123dbh approved these changes

2022-10-15 16:16 UTC, PedroChaparro requested changes

2022-10-15 16:16 UTC, PedroChaparro commented on src/script.js
> +										<img class="img-video" src="${element.thumbnail}" alt="" />
El atributo alt de la imágen está vacío, no es extremadamente grave, pero ya que se deben cambiar otras cosas, puede agregarlo. Propongo usar `${elem.title} youtube thumbnail`.

2022-10-15 16:16 UTC, PedroChaparro commented on src/script.js
> +				loading();
Estos `else{loading()}` hacen que las cards deban ser eliminadas y creadas de nuevo en algunos casos donde no es necesario. Propongo llamar al `loading()` solo al inicio del método, debajo del `preventDefault()`.

2022-10-15 16:16 UTC, PedroChaparro commented on src/script.js
> +	intervalID = setInterval(async () => {
Intente enviar dos búsquedas al tiempo (sin esperar que llegue el resultado de la primera para hacer la segunda). En mi caso llega la primera correctamente pero **se queda pidiendo el mismo uuid a la api de scala**, por lo que nunca pide la segunda búsqueda y se queda mostrando errores en consola.

Ahora les envío un vídeo para que quede más clarol.

2022-10-16 15:24 UTC, PedroChaparro approved these changes
TODO: Refactor in different file.

2022-10-16 15:24 UTC, merged