Store search query into cookie
PedroChaparro/PI202202-alako-frontend pull request #18
Opened 2022-10-13 17:23 UTC by Woynert

- Se guardan en el historial aquellos términos de búsqueda cuyos resultados el usuario haya clickeado.
- Se asegura que no hayan entradas repetidas.
- Momentáneamente no tiene limite; de esto @andres123dbh se encargará.

2022-10-16 15:45 UTC, PedroChaparro requested changes
Hice el merge con development para traer los nuevos cambios del Pull Request de Silvia, pero solo me sirve el evento de click en la última card.

2022-10-22 01:04 UTC, PedroChaparro commented on src/storage.js
> +		const newHist = hist.filter((item, index) => hist.indexOf(item) === index);
¿Le parece si se combierte el `item` a mayúscula? Para evitar resultados repetidos como: Latin **m**usic y Latin **M**usic

2022-10-22 01:05 UTC, PedroChaparro approved these changes
Genial, se ve muy ordenado el código.

2022-10-22 12:17 UTC, Woynert commented on src/storage.js
> +		const newHist = hist.filter((item, index) => hist.indexOf(item) === index);
Buena idea ¿alguna razón para que sea mayúscula y no minúscula?

2022-10-22 12:19 UTC, PedroChaparro commented on src/storage.js
> +		const newHist = hist.filter((item, index) => hist.indexOf(item) === index);
No, creo que con cualquiera podría funcionar, aunque quizá sea mejor en minúscula para no modificar tanto la búsqueda

2022-10-22 14:09 UTC, andres123dbh approved these changes

2022-10-23 14:30 UTC, SilviaPabon approved these changes

2022-10-23 14:30 UTC, merged