Update README.md
PedroChaparro/PI202202-alako-frontend pull request #21
Opened 2022-10-28 00:44 UTC by PedroChaparro

Creación del archivo readme.

2022-10-28 13:10 UTC, Woynert requested changes
Since this is the frontend I believe it'd great to show a screenshot

2022-10-28 15:43 UTC, Woynert approved these changes

2022-10-28 20:48 UTC, SilviaPabon approved these changes

2022-10-29 15:07 UTC, andres123dbh approved these changes

2022-10-29 15:07 UTC, merged